### PR TITLE
Updated to indigo

### PR DESCRIPTION
**Pull request by peci1**
I'm not sure if PR is the best way to do it, since I try to merge update to indigo with your hydro branch, but I haven't found a better way of doing the update. If you could also update rosjava_maven_repo, I'd be really glad.

### CODE REVIEW

**Comment by stonier** [comment]
Hydro has a fair bit of infrastructure keeping that up to date.
- Dynamic dependency updates and tagging

Every night there is a jenkins job that crawls the rosdistro repo database and looks for packages that depend on `message_generation`. These it adds to `rosjava_message`'s dependencies in the `package.xml` and creates a new tag.
- Occasionally I'll release a tag to the build farm and get a deb built for it.
- At the same time I'll upload the new and modified artifacts to the [rosjava_mvn_repo](https://github.com/rosjava/rosjava_mvn_repo)

So...a manual update/fix of hydro's package.xml won't do anything here.

**Comment by stonier** [comment]
The reason I don't have an indigo branch here is because I was looking to drop rosjava message generation like this. It's better than it used to be pre-hydro, but it's still inconvenient.

The new indigo from [source instructions](http://wiki.ros.org/rosjava/Tutorials/indigo/Installation)  actually build messages on the fly (like python and c++), but it's slow and requires you to have all the sources in your workspace or an underlay. Since it's slow, it hasn't made it to 'official' status yet and we need a better way.

I had a hangout with damon late last year to discuss ways to make it happen, but just haven't had a chance to attack this yet.

Does building with those source instructions work for you? If you do that, pull request upgraded versions to our  rosjava maven repo, then that should help you build things down the line without needing the entire source workspace for everything else.

**Comment by stonier** [comment]
Closing this here as it won't go in. If you'd like to keep discussing the message generation on indigo problem, please open a new thread.

**Comment by peci1** [comment]
Yes, I succeeded catkin_making the whole ROS with my project added, and as a result I got the needed JAR files. However, the compilation takes forever, and the need to keep ROS sources on the machine is also very bad. And I also had problems running ROS programs when the ROS-source workspace was loaded along with my workspace. So I essentially need to merge the two workspaces, build them, copy-out the JAR files, then remove the ROS-Source workspace, clean the build files, and build my workspace from scratch. Wow, that's a lot of work. So you say if I "maintain" the Indigo JAR files and send them via a PR, you'd merge that?

**Comment by stonier** [comment]
Maintaining jars - the best way to do this is put them up on the [rosjava maven repo](https://github.com/rosjava/rosjava_mvn_repo). This [tutorial](http://wiki.ros.org/rosjava/Tutorials/indigo/Uploading%20to%20Maven%20on%20Github) might help make this clearer.

I just compiled and pushed the core rosjava stacks and ocmmon msgs last night (0.2 versions). You can see them in [this commit](https://github.com/rosjava/rosjava_mvn_repo/commit/862af53086624d07e898996db713f95f6efb071d) - click on the '333 changed files'.

Once you have things in that repo (or a private fork of it), you don't need them in your source workspace anymore.

First step for indigo will be making that rosjava maven repo up to date and more complete.

**Pull request closed without merging**
